%YAML:1.0

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 613.493408203125
Camera.fy: 612.7874755859375
Camera.cx: 426.18560791015625
Camera.cy: 244.3054962158203

# Camera distortion parameters (OpenCV)
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0

Camera.width: 848
Camera.height: 480

# IR projector baseline times fx (aprox.)
Camera.bf: 9.052

# Camera frames per second
Camera.fps: 4.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 60.0

# Deptmap values factor (what pixel value in the depth image corresponds to 1m?)
DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 2500

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 15
ORBextractor.minThFAST: 5
